# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: backend      # Matching deployment label
  ports:
  - port: 8080        # Service port
    targetPort: 8080  # Container port
    protocol: TCP
    name: http
